title: Tabula Spreadsheet Extraction
description: Have a PDF that used to be a spreadsheet? This Add-On runs the open source [Tabula library](https://tabula.technology) against a selected PDF and tries to identify and extract any spreadsheets it identifies. You can provide a Tabula template you've generated already to run against the documents. 
type: object
documents:
  - selected
  - query
properties: 
  url: 
    title: URL of tabula template
    type: string
    format: uri
